#pragma once

namespace features {
    enum class EBuffType : unsigned char {
        internal = 0,
        aura,
        combat_enchancer,
        combat_dehancer,
        spell_shield,
        stun,
        invisibility,
        silence,
        taunt,
        berserk,
        polymorph,
        slow,
        snare,
        damage,
        heal,
        haste,
        spell_immunity,
        physical_immunity,
        invulnerability,
        attack_speed_slow,
        near_sight,
        currency,
        fear,
        charm,
        poison,
        suppression,
        blind,
        counter,
        shred,
        flee,
        knockup,
        knockback,
        disarm,
        grounded,
        drowsy,
        asleep,
        obscured,
        clickproof_to_enemies,
        un_killable,
        unknown
    };

    enum class EItemId {
        unknown                   = 0,
        boots                     = 1001,
        recurve_bow               = 1043,
        doran_shield              = 1054,
        doran_ring                = 1056,
        health_potion             = 2003,
        kircheis_shard            = 2015,
        refillable_potion         = 2031,
        corrupting_potion         = 2033,
        control_ward              = 2055,
        shurelyas_battlesong      = 2065,
        stopwatch                 = 2420,
        slightly_magical_boots    = 2422,
        manamune                  = 3004,
        berserkers_greaves        = 3006,
        boots_of_swiftness        = 3009,
        sorcerers_shoes           = 3020,
        mortal_reminder           = 3033,
        phantom_dancer            = 3046,
        plated_steelcaps          = 3047,
        zekes_convergence         = 3050,
        steraks_cage              = 3053,
        sheen                     = 3057,
        tear_of_goddess           = 3070,
        triforce                  = 3078,
        runaans_hurricane         = 3085,
        zeal                      = 3086,
        wits_end                  = 3091,
        rapidfire_cannon          = 3094,
        stormrazor                = 3095,
        lichbane                  = 3100,
        redemption                = 3107,
        knights_vow               = 3109,
        mercurys_treads           = 3111,
        nashors_tooth             = 3115,
        mobility_boots            = 3117,
        rageblade                 = 3124,
        mercurial_scimitar        = 3139,
        quicksilver_sash          = 3140,
        youmuus_ghostblade        = 3142,
        randuins_omen             = 3143,
        hextech_rocketbelt        = 3152,
        blade_of_ruined_king      = 3153,
        hexdrinker                = 3155,
        maw_of_malmortius         = 3156,
        zhonyas_hourglass         = 3157,
        boots_of_lucidity         = 3158,
        locket_of_the_iron_solari = 3190,
        gargoyle_stoneplate       = 3193,
        mikaels_blessing          = 3222,
        ward_trinket              = 3340,
        essence_reaver            = 3508,
        frostfang                 = 3851,
        shard_of_true_ice         = 3853,
        harrowing_cresent         = 3863,
        blackmist_scythe          = 3864,
        ironspike_whip            = 6029,
        silvermere_dawn           = 6035,
        goredrinker               = 6630,
        stridebreaker             = 6631,
        divine_sunderer           = 6632,
        everfrost                 = 6656,
        turbo_chemtank            = 6664,
        galeforce                 = 6671,
        shieldbow                 = 6673,
        rageknife                 = 6677,
        eclipse                   = 6692,
        prowler_claw              = 6693,
        anathemas_chains          = 8001
    };

    enum class EHeroes {
        null,
        aatrox       = 266,
        ahri         = 103,
        akali        = 84,
        alistar      = 12,
        amumu        = 32,
        anivia       = 34,
        annie        = 1,
        aphelios     = 523,
        ashe         = 22,
        aurelion_sol = 136,
        azir         = 268,
        bard         = 432,
        blitzcrank   = 53,
        brand        = 63,
        braum        = 201,
        caitlyn      = 51,
        camille      = 164,
        cassiopeia   = 69,
        chogath      = 31,
        corki        = 42,
        darius       = 122,
        diana        = 131,
        draven       = 119,
        dr_mundo     = 36,
        ekko         = 245,
        elise        = 60,
        evelynn      = 28,
        ezreal       = 81,
        fiddlesticks = 9,
        fiora        = 114,
        fizz         = 105,
        galio        = 3,
        gangplank    = 41,
        garen        = 86,
        gnar         = 150,
        gragas       = 79,
        graves       = 104,
        gwen         = 887,
        hecarim      = 120,
        heimerdinger = 74,
        illaoi       = 420,
        irelia       = 39,
        ivern        = 427,
        janna        = 40,
        jarvan_iv    = 59,
        jax          = 24,
        jayce        = 126,
        jhin         = 202,
        jinx         = 222,
        kaisa        = 145,
        kalista      = 429,
        karma        = 43,
        karthus      = 30,
        kassadin     = 38,
        katarina     = 55,
        kayle        = 10,
        kayn         = 141,
        kennen       = 85,
        khazix       = 121,
        kindred      = 203,
        kled         = 240,
        kog_maw      = 96,
        leblanc      = 7,
        lee_sin      = 64,
        leona        = 89,
        lillia       = 876,
        lissandra    = 127,
        lucian       = 236,
        lulu         = 117,
        lux          = 99,
        malphite     = 54,
        malzahar     = 90,
        maokai       = 57,
        master_yi    = 11,
        miss_fortune = 21,
        monkey_king  = 62,
        mordekaiser  = 82,
        morgana      = 25,
        nami         = 267,
        nasus        = 75,
        nautilus     = 111,
        neeko        = 518,
        nidalee      = 76,
        nocturne     = 56,
        nunu         = 20,
        olaf         = 2,
        orianna      = 61,
        ornn         = 516,
        pantheon     = 80,
        poppy        = 78,
        pyke         = 555,
        qiyana       = 246,
        quinn        = 133,
        rakan        = 497,
        rammus       = 33,
        rek_sai      = 421,
        rell         = 526,
        renekton     = 58,
        rengar       = 107,
        riven        = 92,
        rumble       = 68,
        ryze         = 13,
        samira       = 360,
        sejuani      = 113,
        senna        = 235,
        seraphine    = 147,
        sett         = 875,
        shaco        = 35,
        shen         = 98,
        shyvana      = 102,
        singed       = 27,
        sion         = 14,
        sivir        = 15,
        skarner      = 72,
        sona         = 37,
        soraka       = 16,
        swain        = 50,
        sylas        = 517,
        syndra       = 134,
        tahm_kench   = 223,
        taliyah      = 163,
        talon        = 91,
        taric        = 44,
        teemo        = 17,
        thresh       = 412,
        tristana     = 18,
        trundle      = 48,
        tryndamere   = 23,
        twisted_fate = 4,
        twitch       = 29,
        udyr         = 77,
        urgot        = 6,
        varus        = 110,
        vayne        = 67,
        veigar       = 45,
        velkoz       = 161,
        vi           = 254,
        viego        = 234,
        viktor       = 112,
        vladimir     = 8,
        volibear     = 106,
        warwick      = 19,
        xayah        = 498,
        xerath       = 101,
        xin_zhao     = 5,
        yasuo        = 157,
        yone         = 777,
        yorick       = 83,
        yuumi        = 350,
        zac          = 154,
        zed          = 238,
        ziggs        = 115,
        zilean       = 26,
        zoe          = 142,
        zyra         = 143,
        vex          = 711,
        zeri         = 221,
        belveth      = 9999,
        akshan       = 9991,
        nilah        = 9990
    };

    enum class EDamageType {
        true_damage,
        physical_damage,
        magic_damage
    };

    namespace helper {
        // local player specific
        auto get_current_hero( ) -> EHeroes;
        auto calculate_damage( float raw_damage, int16_t target_index, bool physical_damage ) -> float;
        auto get_aa_damage( int16_t target_index, bool on_hit = true ) -> float;
        auto get_onhit_damage( int16_t target_index ) -> float;
        auto get_real_health(
            int16_t     target_index,
            EDamageType damage_type,
            float       delay               = 0.f,
            bool        predict_ally_damage = false
        ) -> float;

        // all champions
        auto get_champion_hero( hash_t name_hash ) -> EHeroes;
        auto process_damage(
            float   raw_damage,
            int16_t source_index,
            int16_t target_index,
            bool    physical_damage
        ) -> float;
        auto get_champion_autoattack_damage(
            int16_t source_index,
            int16_t target_index,
            float   server_cast_time,
            bool    is_melee  = true,
            bool    on_hit    = true,
            bool    will_crit = false
        )
            -> float;
        auto get_champion_onhit_damage(
            int16_t source_index,
            int16_t target_index,
            bool    is_melee,
            float   server_cast_time
        ) -> float;

        auto get_spell_damage(
            hash_t  spell_name,
            int16_t source_index,
            int16_t target_index,
            float   server_cast_time,
            float   impact_time
        ) -> float;

        auto get_incoming_damage( int16_t target_index, float delay = 0.f ) -> float;

        auto is_position_near_turret(
            const sdk::math::Vec3& position,
            bool                   ally_turret      = false,
            float                  nearby_threshold = 500.f
        ) -> bool;
        auto is_position_under_turret( const sdk::math::Vec3& position, bool ally_turret = false ) -> bool;
        auto get_nearby_champions_count(
            const sdk::math::Vec3& position,
            bool                   allies           = false,
            float                  nearby_threshold = 500.f
        ) -> int;
        auto is_wall_in_line( const sdk::math::Vec3& start, const sdk::math::Vec3& end ) -> bool;

        // evade
        auto get_missile_hitbox_polygon(Vec3 start, Vec3 end, float radius) -> sdk::math::Polygon;

        // zeri dmg shit
        auto zeri_execute_threshold( int level = 0, float ability_power = 0.f ) -> float;
        auto get_zeri_charge_base_damage( int level = 0 ) -> float;
        auto get_zeri_charge_max_health_modifier( int level = 0 ) -> float;
    }
}
